---
title: "Problem2"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(p8105.datasets)
library(tidyverse)
library(viridis)
library(plotly)
```


```{r}
data("instacart")
mydata = instacart
mydata
  
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
#Total number of items (n>1k) sold in each aisle 
mydata %>% 
  group_by(aisle_id, aisle) %>% 
  summarize(n = n()) %>% 
  filter(n > 10000) %>% 
  ungroup(aisle) %>% 
  mutate(aisle = fct_reorder(aisle, n)) %>% 
  plot_ly(x = ~aisle, y = ~n, type = 'bar', color = ~aisle) %>% 
  layout(xaxis = list(title = 'Aisle'), yaxis = list(title = 'Number'))


```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
#boxplot of the hour of the day when users order items 
#for the first ten popular asile in which  items are ordered the most
popular_aisle = 
  mydata %>% 
  count(aisle, sort = T) %>% 
  top_n(10)

inner_join(popular_aisle, mydata, by = 'aisle') %>% 
  select(aisle, order_hour_of_day) %>% 
  mutate(aisle = fct_reorder(aisle, order_hour_of_day)) %>% 
  plot_ly(color = ~aisle, y = ~order_hour_of_day, type = 'box') %>% 
  layout(xaxis = list(title = 'Aisle'), yaxis = list(title = 'Hour'))
  

```

### Chart C

```{r}

```

